- name: Desplegar NGINX desde ACR en Podman
  hosts: vm_ubuntu
  become: true

  vars_files:
    - vars.yml

  tasks:
    - name: Autenticarse en el ACR desde Podman
      command: >
        podman login {{ acr_login_server }} -u {{ acr_username }} -p {{ acr_password }}
      register: acr_login_result
      changed_when: "'Login Succeeded' in acr_login_result.stdout"

    - name: Descargar la imagen desde ACR
      command: >
        podman pull {{ acr_login_server }}/{{ image_name }}

    - name: Ejecutar contenedor NGINX con puerto 80
      command: >
        podman run -d --name {{ container_name }} -p 80:80 {{ acr_login_server }}/{{ image_name }}
      args:
        creates: "/var/lib/containers/storage/overlay-containers/{{ container_name }}"

    - name: Habilitar el reenvío del tráfico al puerto 80 (firewalld)
      command: firewall-cmd --add-port=80/tcp --permanent
      ignore_errors: true

    - name: Recargar firewalld
      command: firewall-cmd --reload
      ignore_errors: true
