---
- name: Instalar Podman
  hosts: vm_ubuntu
  become: yes
  vars:
    podman_package: podman

  tasks:
    - name: Actualizar caché de apt
      apt:
        update_cache: yes

    - name: Instalar paquete Podman
      apt:
        name: "{{ podman_package }}"
        state: present

    - name: Verificar versión de Podman
      command: podman --version
      register: podman_version
      changed_when: false

    - debug:
        msg: "Podman instalado: {{ podman_version.stdout }}"
